language: crystal
services:
  - postgresql
script:
  - crystal spec
  - env POSTGRESQL_URL=$POSTGRESQL_URL crystal spec db_spec
  - crystal docs
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: docs
before_script:
  - psql -c 'create database test;' -U postgres
  - psql $POSTGRESQL_URL < spec/migration.sql
env:
  - POSTGRESQL_URL=postgres://postgres@localhost:5432/test
