language: crystal
services:
  - postgresql
script:
  - crystal spec
  - crystal docs
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: docs
before_script:
  - psql -c 'create database core_test;' -U postgres
  - psql $DATABASE_URL < spec/migration.sql
env:
  - DATABASE_URL=postgres://postgres@localhost:5432/core_test
