language: crystal
services:
  - postgresql
cache:
  directories:
    - lib
jobs:
  include:
    - stage: Tests
      name: Crystal spec
      script:
        - crystal spec
    - name: PostgreSQL spec
      env:
        - POSTGRESQL_URL=postgres://postgres@localhost:5432/test
      before_script:
        - psql -c 'create database test;' -U postgres
        - psql $POSTGRESQL_URL < db_spec/pg/migration.sql
      script:
        - env POSTGRESQL_URL=$POSTGRESQL_URL crystal spec db_spec/pg
    - name: SQLite3 spec
      env: $SQLITE3_URL=sqlite3://./test.sqlite3
      before_script:
        - sqlite3 ./test.sqlite3 < db_spec/sqlite3/migration.sql
      script:
        - env SQLITE3_URL=$SQLITE3_URL crystal spec db_spec/sqlite3
    - stage: Deployment
      script:
        - crystal docs
      deploy:
        provider: pages
        skip_cleanup: true
        keep_history: true
        github_token: $GITHUB_TOKEN
        on:
          tags: true
          condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$
        local_dir: docs
addons:
  postgresql: "9.5"
